"""Pure functions: turn manifest + step results into coverage + markdown."""

from __future__ import annotations

from dataclasses import dataclass, field

from tour.capability import Capability
from tour.manifest import Manifest


@dataclass(frozen=True)
class StepResult:
    name: str
    ok: bool
    detail: str
    # Each surfaced fact is (rule_token, qualname) — e.g.
    # ("PY-WL-101", "specimen.trust_flow.unsafe_account_key") or
    # ("dead-entity", "specimen.dead_code.orphaned_helper"). Carrying the qualname
    # (not just the token) is what lets coverage match a SPECIFIC lacuna, so the
    # gate is not hollow: an incidental `dead-entity` on some other symbol must not
    # credit the planted one.
    surfaced: tuple[tuple[str, str], ...] = field(default=())


@dataclass(frozen=True)
class Coverage:
    demonstrated_ids: set[str]
    missing_ids: set[str]


def coverage(manifest: Manifest, results: list[StepResult]) -> Coverage:
    pairs = {p for r in results for p in r.surfaced}
    demonstrated = {
        l.id
        for l in manifest.lacunae
        if any(rule == l.expected_rule and l.symbol in (name or "") for rule, name in pairs)
    }
    missing = {l.id for l in manifest.lacunae} - demonstrated
    return Coverage(demonstrated_ids=demonstrated, missing_ids=missing)


def render_tour_md(results: list[StepResult]) -> str:
    lines = ["# Lacuna — the tour", "", "_Generated by `make tour`. Do not edit by hand._", ""]
    for r in results:
        mark = "✅" if r.ok else "⚠️"
        lines.append(f"## {mark} {r.name}")
        lines.append("")
        lines.append(r.detail or "_(no detail)_")
        lines.append("")
    return "\n".join(lines)


def render_matrix_md(manifest: Manifest, capabilities: list[Capability]) -> str:
    lines = ["# Loom combination matrix coverage", "",
             "_Generated by `make tour`. Do not edit by hand._", ""]
    for cap in capabilities:
        state = cap.detail if not cap.available else "live"
        lines.append(f"- **{cap.name}** — {state}")
    lines.append("")
    lines.append("## Cells exercised by planted lacunae")
    lines.append("")
    for cell in sorted(manifest.cells()):
        lines.append(f"- `{cell}`")
    return "\n".join(lines) + "\n"
